### ISSUE TITLE
DatumFactory is not an ImageIO SPI class

### ISSUE THREAD

**Issue by hulyayurtman** [tum-gis/cesium-point-cloud-generator#2]
Hi,
I execute the jar with the small data you've provied. But I get an error that says DatumFactory is not an ImageIO SPI class. 
![image](https://user-images.githubusercontent.com/7858990/78894383-9b179e00-7a75-11ea-9e55-aed2815624ef.png)

**Comment by onderaltintas** [comment]
Hello Hulya, how are you? I hope you are doing well, 

That problem happens because of you are not using java version 8 but some new java. It seems to happen in newer versions because of geotools library. If you could install earlier sdks, it will work. I did not yet to try newer version geotools but this might be a solution as well. 

Stay strong, stay long

**Comment by hulyayurtman** [comment]
Oh thank you man!
